//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleo.Web.Check {
    
    
    public partial class FirstLook {
        
        /// <summary>
        /// chkServerSideTest control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Web.Controls.Check chkServerSideTest;
        
        /// <summary>
        /// chkClientSideDisabled control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Web.Controls.Check chkClientSideDisabled;
        
        /// <summary>
        /// chkServerSidePostback control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Web.Controls.Check chkServerSidePostback;
        
        /// <summary>
        /// chkControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Web.Controls.Check chkControl;
    }
}
