//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleo.Tests.Messaging {
    
    
    public partial class ManyMessagesSample {
        
        /// <summary>
        /// mm01 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Tests.Messaging.ManyMessages mm01;
        
        /// <summary>
        /// mm02 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Tests.Messaging.ManyMessages mm02;
        
        /// <summary>
        /// mm03 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Tests.Messaging.ManyMessages mm03;
        
        /// <summary>
        /// mm04 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Tests.Messaging.ManyMessages mm04;
        
        /// <summary>
        /// mm05 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Tests.Messaging.ManyMessages mm05;
    }
}
