<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Updating.aspx.cs" Inherits="Nucleo.Tests.DataSource.Updating" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="body" runat="server">

	<asp:GridView ID="gvw" runat="server" DataSourceID="vds" 
		DataKeyNames="Key" AllowSorting="true" AllowPaging="true"
		AutoGenerateDeleteButton="true" AutoGenerateEditButton="true"
		AutoGenerateColumns="false">
		<Columns>
			<asp:BoundField HeaderText="Region" DataField="Region" />
			<asp:BoundField HeaderText="State" DataField="Name" />
		</Columns>	
	</asp:GridView>


	<n:ViewDataSource ID="vds" runat="server" DataObjectTypeName="Nucleo.Tests.DataSource.TestClass,Nucleo.OnlineMVPTests"
		SelectMethod="GetAll" InsertMethod="AddNew" UpdateMethod="Update" DeleteMethod="Delete" />

</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="scripts" runat="server">
</asp:Content>

