//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleo.Demos.MvpSamples.MessagingSamples.EventTypes {
    
    
    public partial class FirstLook {
        
        /// <summary>
        /// EntityTypeSender1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Demos.MvpSamples.MessagingSamples.EventTypes.EntityTypeSender EntityTypeSender1;
        
        /// <summary>
        /// EntityTypeReceiver1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Demos.MvpSamples.MessagingSamples.EventTypes.EntityTypeReceiver EntityTypeReceiver1;
        
        /// <summary>
        /// GenericEntityTypeSender1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Demos.MvpSamples.MessagingSamples.EventTypes.GenericEntityTypeSender GenericEntityTypeSender1;
        
        /// <summary>
        /// GenericEntityTypeReceiver1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Demos.MvpSamples.MessagingSamples.EventTypes.GenericEntityTypeReceiver GenericEntityTypeReceiver1;
        
        /// <summary>
        /// EntityInstanceSender1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Demos.MvpSamples.MessagingSamples.EventTypes.EntityInstanceSender EntityInstanceSender1;
        
        /// <summary>
        /// EntityInstanceReceiver1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Demos.MvpSamples.MessagingSamples.EventTypes.EntityInstanceReceiver EntityInstanceReceiver1;
        
        /// <summary>
        /// TextIdentifierSender1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Demos.MvpSamples.MessagingSamples.EventTypes.TextIdentifierSender TextIdentifierSender1;
        
        /// <summary>
        /// TextIdentifierReceiver1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Demos.MvpSamples.MessagingSamples.EventTypes.TextIdentifierReceiver TextIdentifierReceiver1;
    }
}
