//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Nucleo.TestData.Entities
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class IntegrationTestDataObjectContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new IntegrationTestDataObjectContext object using the connection string found in the 'IntegrationTestDataObjectContext' section of the application configuration file.
        /// </summary>
        public IntegrationTestDataObjectContext() : base("name=IntegrationTestDataObjectContext", "IntegrationTestDataObjectContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new IntegrationTestDataObjectContext object.
        /// </summary>
        public IntegrationTestDataObjectContext(string connectionString) : base(connectionString, "IntegrationTestDataObjectContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new IntegrationTestDataObjectContext object.
        /// </summary>
        public IntegrationTestDataObjectContext(EntityConnection connection) : base(connection, "IntegrationTestDataObjectContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DataContextManagerTestData> DataContextManagerTestDatas
        {
            get
            {
                if ((_DataContextManagerTestDatas == null))
                {
                    _DataContextManagerTestDatas = base.CreateObjectSet<DataContextManagerTestData>("DataContextManagerTestDatas");
                }
                return _DataContextManagerTestDatas;
            }
        }
        private ObjectSet<DataContextManagerTestData> _DataContextManagerTestDatas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ObjectContextManagerTestData> ObjectContextManagerTestDatas
        {
            get
            {
                if ((_ObjectContextManagerTestDatas == null))
                {
                    _ObjectContextManagerTestDatas = base.CreateObjectSet<ObjectContextManagerTestData>("ObjectContextManagerTestDatas");
                }
                return _ObjectContextManagerTestDatas;
            }
        }
        private ObjectSet<ObjectContextManagerTestData> _ObjectContextManagerTestDatas;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DataContextManagerTestDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDataContextManagerTestDatas(DataContextManagerTestData dataContextManagerTestData)
        {
            base.AddObject("DataContextManagerTestDatas", dataContextManagerTestData);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ObjectContextManagerTestDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToObjectContextManagerTestDatas(ObjectContextManagerTestData objectContextManagerTestData)
        {
            base.AddObject("ObjectContextManagerTestDatas", objectContextManagerTestData);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Nucleo.TestData.Entities", Name="DataContextManagerTestData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DataContextManagerTestData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DataContextManagerTestData object.
        /// </summary>
        /// <param name="dataContextManagerTestDataKey">Initial value of the DataContextManagerTestDataKey property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="sortOrder">Initial value of the SortOrder property.</param>
        /// <param name="createdDate">Initial value of the CreatedDate property.</param>
        public static DataContextManagerTestData CreateDataContextManagerTestData(global::System.Guid dataContextManagerTestDataKey, global::System.String name, global::System.Int32 sortOrder, global::System.DateTime createdDate)
        {
            DataContextManagerTestData dataContextManagerTestData = new DataContextManagerTestData();
            dataContextManagerTestData.DataContextManagerTestDataKey = dataContextManagerTestDataKey;
            dataContextManagerTestData.Name = name;
            dataContextManagerTestData.SortOrder = sortOrder;
            dataContextManagerTestData.CreatedDate = createdDate;
            return dataContextManagerTestData;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid DataContextManagerTestDataKey
        {
            get
            {
                return _DataContextManagerTestDataKey;
            }
            set
            {
                if (_DataContextManagerTestDataKey != value)
                {
                    OnDataContextManagerTestDataKeyChanging(value);
                    ReportPropertyChanging("DataContextManagerTestDataKey");
                    _DataContextManagerTestDataKey = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DataContextManagerTestDataKey");
                    OnDataContextManagerTestDataKeyChanged();
                }
            }
        }
        private global::System.Guid _DataContextManagerTestDataKey;
        partial void OnDataContextManagerTestDataKeyChanging(global::System.Guid value);
        partial void OnDataContextManagerTestDataKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SortOrder
        {
            get
            {
                return _SortOrder;
            }
            set
            {
                OnSortOrderChanging(value);
                ReportPropertyChanging("SortOrder");
                _SortOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SortOrder");
                OnSortOrderChanged();
            }
        }
        private global::System.Int32 _SortOrder;
        partial void OnSortOrderChanging(global::System.Int32 value);
        partial void OnSortOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Nucleo.TestData.Entities", Name="ObjectContextManagerTestData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ObjectContextManagerTestData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ObjectContextManagerTestData object.
        /// </summary>
        /// <param name="objectContextManagerTestDataKey">Initial value of the ObjectContextManagerTestDataKey property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="sortOrder">Initial value of the SortOrder property.</param>
        /// <param name="createdDate">Initial value of the CreatedDate property.</param>
        public static ObjectContextManagerTestData CreateObjectContextManagerTestData(global::System.Guid objectContextManagerTestDataKey, global::System.String name, global::System.Int32 sortOrder, global::System.DateTime createdDate)
        {
            ObjectContextManagerTestData objectContextManagerTestData = new ObjectContextManagerTestData();
            objectContextManagerTestData.ObjectContextManagerTestDataKey = objectContextManagerTestDataKey;
            objectContextManagerTestData.Name = name;
            objectContextManagerTestData.SortOrder = sortOrder;
            objectContextManagerTestData.CreatedDate = createdDate;
            return objectContextManagerTestData;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ObjectContextManagerTestDataKey
        {
            get
            {
                return _ObjectContextManagerTestDataKey;
            }
            set
            {
                if (_ObjectContextManagerTestDataKey != value)
                {
                    OnObjectContextManagerTestDataKeyChanging(value);
                    ReportPropertyChanging("ObjectContextManagerTestDataKey");
                    _ObjectContextManagerTestDataKey = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ObjectContextManagerTestDataKey");
                    OnObjectContextManagerTestDataKeyChanged();
                }
            }
        }
        private global::System.Guid _ObjectContextManagerTestDataKey;
        partial void OnObjectContextManagerTestDataKeyChanging(global::System.Guid value);
        partial void OnObjectContextManagerTestDataKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SortOrder
        {
            get
            {
                return _SortOrder;
            }
            set
            {
                OnSortOrderChanging(value);
                ReportPropertyChanging("SortOrder");
                _SortOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SortOrder");
                OnSortOrderChanged();
            }
        }
        private global::System.Int32 _SortOrder;
        partial void OnSortOrderChanging(global::System.Int32 value);
        partial void OnSortOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();

        #endregion
    
    }

    #endregion
    
}
