//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleo.Web.FormItemDisplay {
    
    
    public partial class CustomTemplates {
        
        /// <summary>
        /// fc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Web.FormControls.FormItemContainer fc;
        
        /// <summary>
        /// fs1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Web.FormControls.FormItemSection fs1;
        
        /// <summary>
        /// fs2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Web.FormControls.FormItemSection fs2;
    }
}
