//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleo.Demos.MvpScenarios.TabbedForms {
    
    
    public partial class Parent {
        
        /// <summary>
        /// ucContactInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Demos.MvpScenarios.TabbedForms.ContactInfo ucContactInfo;
        
        /// <summary>
        /// ucAddresses control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Demos.MvpScenarios.TabbedForms.Addresses ucAddresses;
        
        /// <summary>
        /// ucPhoneNumbers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Demos.MvpScenarios.TabbedForms.PhoneNumbers ucPhoneNumbers;
        
        /// <summary>
        /// ucDisplay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Demos.MvpScenarios.TabbedForms.Display ucDisplay;
    }
}
