//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleo.Demos.MvpSamples.MessagingSamples {
    
    
    public partial class FirstLook {
        
        /// <summary>
        /// MessageSender1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Demos.MvpSamples.MessagingSamples.FirstLookSender MessageSender1;
        
        /// <summary>
        /// MessageReceiver1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Demos.MvpSamples.MessagingSamples.FirstLookReceiver MessageReceiver1;
    }
}
