//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nucleo.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The control added to the collection is not the correct type..
        /// </summary>
        internal static string ADDED_CONTROL_OF_INVALID_TYPE {
            get {
                return ResourceManager.GetString("ADDED_CONTROL_OF_INVALID_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The control wasn&apos;t found in the cell collection..
        /// </summary>
        internal static string CANT_EXTRACT_CONTROL_IN_CELL {
            get {
                return ResourceManager.GetString("CANT_EXTRACT_CONTROL_IN_CELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the data bound parameters that is required was not provided.  Please provide the field name..
        /// </summary>
        internal static string DATABOUND_FIELD_NOT_PROVIDED {
            get {
                return ResourceManager.GetString("DATABOUND_FIELD_NOT_PROVIDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of the required properties have been set.  Please specify a value for the required properties..
        /// </summary>
        internal static string NO_REQUIRED_PROPERTIES {
            get {
                return ResourceManager.GetString("NO_REQUIRED_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index value specified is out of the range of valid values..
        /// </summary>
        internal static string OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("OUT_OF_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value provided for the {0} is not a valid value..
        /// </summary>
        internal static string PROPERTY_SETTER_INVALID_VALUE {
            get {
                return ResourceManager.GetString("PROPERTY_SETTER_INVALID_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No value has been provided to the property.  Please supply a valid value..
        /// </summary>
        internal static string PROPERTY_VALUE_NOT_PROVIDED {
            get {
                return ResourceManager.GetString("PROPERTY_VALUE_NOT_PROVIDED", resourceCulture);
            }
        }
    }
}
