<%@ Page Title="" Language="C#" MasterPageFile="~/Layout/DemoLayout.Master" AutoEventWireup="true" CodeBehind="Updating.aspx.cs" Inherits="Nucleo.Demos.MvpSamples.DataSource.Updating" %>
<%@ Register TagPrefix="sc" Namespace="Nucleo.Web.Mvp.DataSourceControls" Assembly="Nucleo.Mvp.WebForms" %>

<asp:Content ID="Content1" ContentPlaceHolderID="Head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="CodeSample" runat="server">

	<asp:GridView ID="gvw" runat="server" DataSourceID="vds" 
		DataKeyNames="Key" AllowSorting="true" AllowPaging="true"
		AutoGenerateDeleteButton="true" AutoGenerateEditButton="true"
		AutoGenerateColumns="false">
		<Columns>
			<asp:BoundField HeaderText="Region" DataField="Region" />
			<asp:BoundField HeaderText="State" DataField="Name" />
		</Columns>	
	</asp:GridView>


	<sc:ViewDataSource ID="vds" runat="server" DataObjectTypeName="Nucleo.Tests.DataSource.TestClass,Nucleo.OnlineMVPTests"
		SelectMethod="GetAll" InsertMethod="AddNew" UpdateMethod="Update" DeleteMethod="Delete" />

</asp:Content>
