//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleo.Web.ContentControls.NavigationBars {
    
    
    public partial class FirstLook {
        
        /// <summary>
        /// navContainer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Web.NavigationControls.NavigationBarContainer navContainer;
        
        /// <summary>
        /// navBar1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Web.NavigationControls.NavigationBar navBar1;
        
        /// <summary>
        /// navBarItem1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Web.NavigationControls.NavigationBarItem navBarItem1;
        
        /// <summary>
        /// navBarItem2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Web.NavigationControls.NavigationBarItem navBarItem2;
        
        /// <summary>
        /// navBarItem3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Web.NavigationControls.NavigationBarItem navBarItem3;
        
        /// <summary>
        /// navBarItem4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Web.NavigationControls.NavigationBarItem navBarItem4;
        
        /// <summary>
        /// navBar2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Web.NavigationControls.NavigationBar navBar2;
        
        /// <summary>
        /// NavigationBarItem1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Web.NavigationControls.NavigationBarItem NavigationBarItem1;
        
        /// <summary>
        /// NavigationBarItem2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Web.NavigationControls.NavigationBarItem NavigationBarItem2;
        
        /// <summary>
        /// NavigationBarItem3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Web.NavigationControls.NavigationBarItem NavigationBarItem3;
        
        /// <summary>
        /// NavigationBarItem4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Nucleo.Web.NavigationControls.NavigationBarItem NavigationBarItem4;
    }
}
